$color = rgba(1, 6, 8, 1)
$inner_color = rgba(1, 6, 8, 0.66)
$outer_color = rgba(136, 175, 200, 1)
$font_color = rgba(166, 213, 208, 1)
$placeholder_color = rgba(166, 213, 208, 0.7)
$check_color = rgba(164, 228, 234, 1)
