# Background and foreground colors
background = #010608
foreground = #A6D5D0

# Standard colors
palette = 0=#010608
palette = 1=#7d9b8b
palette = 2=#9acbc6
palette = 3=#c3fcf1
palette = 4=#5f8491
palette = 5=#88afc8
palette = 6=#a4e4ea
palette = 7=#A6D5D0

# Bright colors
palette = 8=#61696b
palette = 9=#8db39e
palette = 10=#a5e5df
palette = 11=#bafff5
palette = 12=#6c9aab
palette = 13=#94c6e7
palette = 14=#aefeff
palette = 15=#eaf8fa
