background            #010608
foreground            #A6D5D0

# black
color0  #010608
color8  #61696b

# red
color1  #7d9b8b
color9  #8db39e

# green
color2  #9acbc6
color10 #a5e5df

# yellow
color3  #c3fcf1
color11 #bafff5

# blue
color4  #5f8491
color12 #6c9aab

# magenta
color5  #88afc8
color13 #94c6e7

#cyan
color6  #a4e4ea
color14 #aefeff

#white
color7  #A6D5D0
color15 #eaf8fa


