// Generated by omarchy-theme-set-templates from the active theme's colors.toml.
// Installed as ~/.config/fastfetch/config.jsonc (symlink). Do not edit — change
// this .tpl (or the theme palette). Requires fastfetch >= 2.42 for #RRGGBB.

{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/master/doc/json_schema.json",
  "logo": {
    "type": "auto",
    "color": {
      "1": "{{ accent }}",
      "2": "{{ blue }}"
    },
    "padding": {
      "top": 2,
      "right": 6,
      "left": 2
    }
  },
  "display": {
    "separator": ": ",
    "color": {
      "keys": "{{ accent }}",
      "title": "{{ foreground }}",
      "output": "{{ foreground }}",
      "separator": "{{ muted }}"
    },
    "percent": {
      "color": {
        "green": "{{ green }}",
        "yellow": "{{ yellow }}",
        "red": "{{ red }}"
      }
    }
  },
  "modules": [
    "break",
    {
      "type": "custom",
      "format": "┌──────────────────────Hardware──────────────────────┐",
      "outputColor": "{{ muted }}"
    },
    {
      "type": "host",
      "key": " PC",
      "keyColor": "{{ green }}"
    },
    {
      "type": "cpu",
      "key": "│ ├",
      "showPeCoreCount": true,
      "keyColor": "{{ green }}"
    },
    {
      "type": "gpu",
      "key": "│ ├",
      "detectionMethod": "pci",
      "keyColor": "{{ green }}"
    },
    {
      "type": "display",
      "key": "│ ├󱄄",
      "keyColor": "{{ green }}"
    },
    {
      "type": "disk",
      "key": "│ ├󰋊",
      "folders": "/",
      "keyColor": "{{ green }}"
    },
    {
      "type": "memory",
      "key": "│ ├",
      "keyColor": "{{ green }}"
    },
    {
      "type": "swap",
      "key": "└ └󰓡",
      "keyColor": "{{ green }}"
    },
    {
      "type": "custom",
      "format": "└────────────────────────────────────────────────────┘",
      "outputColor": "{{ muted }}"
    },
    "break",
    {
      "type": "custom",
      "format": "┌──────────────────────Software──────────────────────┐",
      "outputColor": "{{ muted }}"
    },
    {
      "type": "os",
      "key": "{icon} OS",
      "keyColor": "{{ blue }}"
    },
    {
      "type": "kernel",
      "key": "│ ├",
      "keyColor": "{{ blue }}"
    },
    {
      "type": "wm",
      "key": "│ ├",
      "keyColor": "{{ blue }}"
    },
    {
      "type": "terminal",
      "key": "│ ├",
      "keyColor": "{{ blue }}"
    },
    {
      "type": "shell",
      "key": "│ ├",
      "keyColor": "{{ blue }}"
    },
    {
      "type": "packages",
      "key": "│ ├󰏖",
      "keyColor": "{{ blue }}"
    },
    {
      "type": "command",
      "key": "│ ├󰸌",
      "keyColor": "{{ blue }}",
      "text": "omarchy-theme-current",
      "format": "{result}  {#{{ red }}}●{#{{ yellow }}}●{#{{ green }}}●{#{{ cyan }}}●{#{{ blue }}}●{#{{ magenta }}}●{#{{ accent }}}●{#}"
    },
    {
      "type": "terminalfont",
      "key": "└ └",
      "keyColor": "{{ blue }}"
    },
    {
      "type": "custom",
      "format": "└────────────────────────────────────────────────────┘",
      "outputColor": "{{ muted }}"
    },
    "break",
    {
      "type": "custom",
      "format": "┌──────────────────────Uptime────────────────────────┐",
      "outputColor": "{{ muted }}"
    },
    {
      "type": "command",
      "key": "󱦟 OS Age",
      "keyColor": "{{ magenta }}",
      "text": "birth=$(stat -c %W / 2>/dev/null || echo 0); if [ \"$birth\" -gt 0 ] 2>/dev/null; then echo \"$(( ($(date +%s) - birth) / 86400 )) days\"; else echo unknown; fi"
    },
    {
      "type": "uptime",
      "key": "󱫐 Uptime",
      "keyColor": "{{ magenta }}"
    },
    {
      "type": "custom",
      "format": "└────────────────────────────────────────────────────┘",
      "outputColor": "{{ muted }}"
    },
    "break"
  ]
}
