# Generated by omarchy-theme-set-templates from the active theme's colors.toml.
# Rendered to ~/.local/state/omarchy/current/theme/i3.conf and included at the
# end of ~/.config/i3/config (after config.d/*), so these win over any earlier
# client.* defaults. Do not edit — edit this .tpl.
#
# Derivation mirrors the old scripts/apply_i3_theme.sh mapping:
#   bg/placeholder = background   fg = foreground   indicator = green
#   focused        = accent       focused_inactive = blue
#   urgent         = magenta      unfocused        = lighter_background

set $i3_cl_col_bg   {{ background }}
set $i3_cl_col_fg   {{ foreground }}
set $i3_cl_col_in   {{ green }}
set $i3_cl_col_afoc {{ accent }}
set $i3_cl_col_ifoc {{ blue }}
set $i3_cl_col_ufoc {{ lighter_background }}
set $i3_cl_col_urgt {{ magenta }}
set $i3_cl_col_phol {{ background }}

# class                  border            backgr.           text            indicator       child_border
client.focused           $i3_cl_col_afoc   $i3_cl_col_afoc   $i3_cl_col_bg   $i3_cl_col_in   $i3_cl_col_afoc
client.focused_inactive  $i3_cl_col_ifoc   $i3_cl_col_ifoc   $i3_cl_col_bg   $i3_cl_col_in   $i3_cl_col_ifoc
client.unfocused         $i3_cl_col_ufoc   $i3_cl_col_ufoc   $i3_cl_col_fg   $i3_cl_col_in   $i3_cl_col_ufoc
client.urgent            $i3_cl_col_urgt   $i3_cl_col_urgt   $i3_cl_col_fg   $i3_cl_col_in   $i3_cl_col_urgt
client.placeholder       $i3_cl_col_phol   $i3_cl_col_phol   $i3_cl_col_fg   $i3_cl_col_in   $i3_cl_col_phol
client.background        $i3_cl_col_bg
