# Background and foreground colors
background = #030002
foreground = #F7DCE5

# Standard colors
palette = 0=#030002
palette = 1=#c17b8e
palette = 2=#ffa595
palette = 3=#ffcbc5
palette = 4=#9f6698
palette = 5=#df89b8
palette = 6=#f7bbff
palette = 7=#F7DCE5

# Bright colors
palette = 8=#5d585c
palette = 9=#e28aa2
palette = 10=#ffb29e
palette = 11=#ffc5be
palette = 12=#bc76b4
palette = 13=#ff95d3
palette = 14=#ffcbff
palette = 15=#fef1f6
