$color = rgba(3, 0, 2, 1)
$inner_color = rgba(3, 0, 2, 0.66)
$outer_color = rgba(223, 137, 184, 1)
$font_color = rgba(247, 220, 229, 1)
$placeholder_color = rgba(247, 220, 229, 0.7)
$check_color = rgba(247, 187, 255, 1)
