background            #030002
foreground            #F7DCE5

# black
color0  #030002
color8  #5d585c

# red
color1  #c17b8e
color9  #e28aa2

# green
color2  #ffa595
color10 #ffb29e

# yellow
color3  #ffcbc5
color11 #ffc5be

# blue
color4  #9f6698
color12 #bc76b4

# magenta
color5  #df89b8
color13 #ff95d3

#cyan
color6  #f7bbff
color14 #ffcbff

#white
color7  #F7DCE5
color15 #fef1f6


