# Don't allow new windows to be larger than the screen.
autofit-larger=100%x100%
autofit=60%
# Enable hardware decoding if available, =yes is implied.
hwdec
# Spaces don't have to be escaped.
osd-playing-msg=File: ${filename}
save-position-on-quit
resume-playback=true
watch-later-options=start
