#!/usr/bin/env bash

## Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
##
## Run ncmpcpp with alternate config (kitty)

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/kitty/kitty.conf"

exec kitty --class 'Music,Music' --config "$CONFIG" \
	--override 'initial_window_width=105c' \
	--override 'initial_window_height=22c' \
	-e ~/.ncmpcpp/scripts/ncmpcpp-art
