$color = rgba(11, 5, 23, 1)
$inner_color = rgba(11, 5, 23, 0.66)
$outer_color = rgba(198, 149, 226, 1)
$font_color = rgba(233, 214, 231, 1)
$placeholder_color = rgba(233, 214, 231, 0.7)
$check_color = rgba(198, 208, 255, 1)
