# Background and foreground colors
background = #0B0517
foreground = #E9D6E7

# Standard colors
palette = 0=#0B0517
palette = 1=#b582b1
palette = 2=#a0c2ff
palette = 3=#ffcdff
palette = 4=#8773b5
palette = 5=#c695e2
palette = 6=#c6d0ff
palette = 7=#E9D6E7

# Bright colors
palette = 8=#605f65
palette = 9=#d292ce
palette = 10=#acd7ff
palette = 11=#ffc3ff
palette = 12=#9e84d6
palette = 13=#e3a4ff
palette = 14=#d9e4ff
palette = 15=#f8f3fd
