background            #0B0517
foreground            #E9D6E7

# black
color0  #0B0517
color8  #605f65

# red
color1  #b582b1
color9  #d292ce

# green
color2  #a0c2ff
color10 #acd7ff

# yellow
color3  #ffcdff
color11 #ffc3ff

# blue
color4  #8773b5
color12 #9e84d6

# magenta
color5  #c695e2
color13 #e3a4ff

#cyan
color6  #c6d0ff
color14 #d9e4ff

#white
color7  #E9D6E7
color15 #f8f3fd


